
   `undef A2X_AHB_EBT_MODE
   `undef A2X_AHB_LITE_MODE
   `undef A2X_AHB_LOCKED
   `undef A2X_AHB_RRECALL_DEPTH
   `undef A2X_AHB_SPLIT_MODE
   `undef A2X_APB_MODE
   `undef A2X_ARSBW
   `undef A2X_AR_FIFO_DEPTH
   `undef A2X_AR_FIFO_DEPTH_LOG2
   `undef A2X_AR_SP_PIPELINE
   `undef A2X_AUTO_LINK_SPLIT_MODE
   `undef A2X_AW
   `undef A2X_AWSBW
   `undef A2X_AW_FIFO_DEPTH
   `undef A2X_AW_FIFO_DEPTH_LOG2
   `undef A2X_AW_SP_PIPELINE
   `undef A2X_AXI_INTERFACE_TYPE
   `undef A2X_BLW
   `undef A2X_BOUNDARY_W
   `undef A2X_BRESPW
   `undef A2X_BRESP_FIFO_DEPTH
   `undef A2X_BRESP_FIFO_DEPTH_LOG2
   `undef A2X_BRESP_MODE
   `undef A2X_BRESP_ORDER
   `undef A2X_BSBW
   `undef A2X_BSW
   `undef A2X_BTW
   `undef A2X_B_OSW_LIMIT
   `undef A2X_B_OSW_LIMIT_LOG2
   `undef A2X_B_OSW_LIMIT_P1
   `undef A2X_CLK_IS_SYNC
   `undef A2X_CLK_MODE
   `undef A2X_CTW
   `undef A2X_DOWNSIZE
   `undef A2X_DS_RATIO_2
   `undef A2X_HASBW
   `undef A2X_HAS_AXI4
   `undef A2X_HAS_CNT_M8
   `undef A2X_HAS_HINCR_HCBCNT
   `undef A2X_HAS_NBUF_MODE
   `undef A2X_HAS_SINGLE_RBCNT
   `undef A2X_HAS_SINGLE_WBCNT
   `undef A2X_HBLW
   `undef A2X_HBTYPE_W
   `undef A2X_HCBUF_MODE
   `undef A2X_HCSNF_RLEN
   `undef A2X_HCSNF_WLEN
   `undef A2X_HIDW
   `undef A2X_HINCR_ARLEN_DFLT
   `undef A2X_HINCR_ARLEN_MIN
   `undef A2X_HINCR_AWLEN_DFLT
   `undef A2X_HINCR_AWLEN_MIN
   `undef A2X_HINCR_HCBCNT
   `undef A2X_HINCR_RBCNT_MAX
   `undef A2X_HINCR_RBCNT_MIN
   `undef A2X_HINCR_WBCNT_MAX
   `undef A2X_HINCR_WBCNT_MIN
   `undef A2X_HPTW
   `undef A2X_HREADY_LOW_PERIOD
   `undef A2X_HRESPW
   `undef A2X_IDW
   `undef A2X_INACTIVE_VAL
   `undef A2X_INC_QOS
   `undef A2X_INC_REGION
   `undef A2X_INT_ARSBW
   `undef A2X_INT_AWSBW
   `undef A2X_INT_AXI3
   `undef A2X_INT_BSBW
   `undef A2X_INT_HASBW
   `undef A2X_INT_LTW
   `undef A2X_INT_NUM_AHBM
   `undef A2X_INT_RSBW
   `undef A2X_INT_WSBW
   `undef A2X_IS_DOWNSIZED
   `undef A2X_LKMODE_MAX_PREFETCH
   `undef A2X_LK_RD_FIFO_DEPTH
   `undef A2X_LK_RD_FIFO_DEPTH_LOG2
   `undef A2X_LOCKED
   `undef A2X_LOWPWR_IF
   `undef A2X_LOWPWR_NOPX_CNT
   `undef A2X_LOWPWR_RST_CNT
   `undef A2X_LTW
   `undef A2X_MAX_ALEN
   `undef A2X_MAX_BSBW
   `undef A2X_MAX_PP_TOTAL_BYTES
   `undef A2X_MAX_SP_TOTAL_BYTES
   `undef A2X_MAX_TOTAL_BYTES
   `undef A2X_MAX_TOTAL_BYTES_LOG2
   `undef A2X_NUM_AHBM
   `undef A2X_NUM_URID
   `undef A2X_NUM_UWID
   `undef A2X_N_TESTCASE_DUPLICATION
   `undef A2X_OSAW_LIMIT
   `undef A2X_OSR_EN
   `undef A2X_OSR_LIMIT
   `undef A2X_OSR_LIMIT_LOG2
   `undef A2X_OSR_LIMIT_P1
   `undef A2X_OSW_EN
   `undef A2X_OSW_LIMIT
   `undef A2X_PP_AW
   `undef A2X_PP_BLW
   `undef A2X_PP_DW
   `undef A2X_PP_DW_16
   `undef A2X_PP_DW_32
   `undef A2X_PP_DW_64
   `undef A2X_PP_DW_LOG2
   `undef A2X_PP_ENDIAN
   `undef A2X_PP_IDW
   `undef A2X_PP_IS_AXI
   `undef A2X_PP_MAX_SIZE
   `undef A2X_PP_MODE
   `undef A2X_PP_NUM_BYTES
   `undef A2X_PP_NUM_BYTES_LOG2
   `undef A2X_PP_OSAW_LIMIT
   `undef A2X_PP_OSAW_LIMIT_LOG2
   `undef A2X_PP_OSAW_LIMIT_P1
   `undef A2X_PP_SYNC_DEPTH
   `undef A2X_PP_WSTRB_DW
   `undef A2X_PRIMEPOWER_SIM
   `undef A2X_PTW
   `undef A2X_RBUF_MODE
   `undef A2X_RD_FIFO_DEPTH
   `undef A2X_RD_FIFO_DEPTH_LOG2
   `undef A2X_READ_INTLEV
   `undef A2X_READ_ORDER
   `undef A2X_RRESPW
   `undef A2X_RSBW
   `undef A2X_RSW
   `undef A2X_RS_AR_TMO
   `undef A2X_RS_AW_TMO
   `undef A2X_RS_B_TMO
   `undef A2X_RS_RATIO
   `undef A2X_RS_RATIO_LOG2
   `undef A2X_RS_R_TMO
   `undef A2X_RS_W_TMO
   `undef A2X_SIM_APB_CLK_PERIOD
   `undef A2X_SIM_PP_CLK_PERIOD
   `undef A2X_SIM_SEED
   `undef A2X_SIM_SP_CLK_PERIOD
   `undef A2X_SINGLE_RBCNT
   `undef A2X_SINGLE_WBCNT
   `undef A2X_SNF_ARLEN_DFLT
   `undef A2X_SNF_ARLEN_MIN
   `undef A2X_SNF_AWLEN_DFLT
   `undef A2X_SNF_AWLEN_MIN
   `undef A2X_SP_AW
   `undef A2X_SP_BLW
   `undef A2X_SP_CLK_SKEW
   `undef A2X_SP_DW
   `undef A2X_SP_DW_32
   `undef A2X_SP_DW_LOG2
   `undef A2X_SP_ENDIAN
   `undef A2X_SP_IDW
   `undef A2X_SP_MAX_SIZE
   `undef A2X_SP_NUM_BYTES
   `undef A2X_SP_NUM_BYTES_LOG2
   `undef A2X_SP_OSAW_LIMIT
   `undef A2X_SP_OSAW_LIMIT_LOG2
   `undef A2X_SP_OSAW_LIMIT_P1
   `undef A2X_SP_SYNC_DEPTH
   `undef A2X_SP_WSTRB_DW
   `undef A2X_UPSIZE
   `undef A2X_VERIF_EN
   `undef A2X_WBUF_MODE
   `undef A2X_WD_FIFO_DEPTH
   `undef A2X_WD_FIFO_DEPTH_LOG2
   `undef A2X_WSBW
   `undef ABURST_FIXED
   `undef ABURST_INCR
   `undef ABURST_WRAP
   `undef ADECERR
   `undef AEXOKAY
   `undef AFIXED
   `undef AHB_SPLIT_MODE
   `undef AINCR
   `undef AOKAY
   `undef ASLVERR
   `undef AWRAP
   `undef CT_MODE
   `undef DWC_NO_CDC_INIT
   `undef DWC_NO_TST_MODE
   `undef DW_HOLD_MUX_DELAY
   `undef DW_SETUP_MUX_DELAY
   `undef HBURST_INCR
   `undef HBURST_INCR16
   `undef HBURST_INCR4
   `undef HBURST_INCR8
   `undef HBURST_SINGLE
   `undef HBURST_WRAP16
   `undef HBURST_WRAP4
   `undef HBURST_WRAP8
   `undef HPROT_BUFF
   `undef HPROT_CACHE
   `undef HPROT_DATA
   `undef HPROT_PRIV
   `undef HRESP_ERROR
   `undef HRESP_OKAY
   `undef HRESP_RETRY
   `undef HRESP_SPLIT
   `undef HSIZE_1024
   `undef HSIZE_1024BIT
   `undef HSIZE_128
   `undef HSIZE_128BIT
   `undef HSIZE_16
   `undef HSIZE_16BIT
   `undef HSIZE_256
   `undef HSIZE_256BIT
   `undef HSIZE_32
   `undef HSIZE_32BIT
   `undef HSIZE_512
   `undef HSIZE_512BIT
   `undef HSIZE_64
   `undef HSIZE_64BIT
   `undef HSIZE_8
   `undef HSIZE_8BIT
   `undef HSIZE_BYTE
   `undef HSIZE_WORD1024
   `undef HSIZE_WORD128
   `undef HSIZE_WORD16
   `undef HSIZE_WORD256
   `undef HSIZE_WORD32
   `undef HSIZE_WORD512
   `undef HSIZE_WORD64
   `undef HTRANS_BUSY
   `undef HTRANS_IDLE
   `undef HTRANS_NSEQ
   `undef HTRANS_SEQ
   `undef RM_BCM01
   `undef RM_BCM02
   `undef RM_BCM03
   `undef RM_BCM05
   `undef RM_BCM05_ATV
   `undef RM_BCM06
   `undef RM_BCM06_ATV
   `undef RM_BCM07
   `undef RM_BCM07_ATV
   `undef RM_BCM07_EFES
   `undef RM_BCM08
   `undef RM_BCM09
   `undef RM_BCM09_DP
   `undef RM_BCM09_ECC
   `undef RM_BCM10
   `undef RM_BCM11
   `undef RM_BCM12
   `undef RM_BCM15
   `undef RM_BCM16
   `undef RM_BCM21
   `undef RM_BCM21_A
   `undef RM_BCM21_ATV
   `undef RM_BCM21_CG
   `undef RM_BCM22
   `undef RM_BCM22_ATV
   `undef RM_BCM23
   `undef RM_BCM23_ATV
   `undef RM_BCM23_C
   `undef RM_BCM24
   `undef RM_BCM24_AP
   `undef RM_BCM25
   `undef RM_BCM25_ATV
   `undef RM_BCM25_C
   `undef RM_BCM26
   `undef RM_BCM27
   `undef RM_BCM28
   `undef RM_BCM29
   `undef RM_BCM30
   `undef RM_BCM31
   `undef RM_BCM32
   `undef RM_BCM35
   `undef RM_BCM35_T
   `undef RM_BCM36
   `undef RM_BCM36_NHS
   `undef RM_BCM37
   `undef RM_BCM38
   `undef RM_BCM38_ADP
   `undef RM_BCM38_AP
   `undef RM_BCM38_ECC
   `undef RM_BCM39
   `undef RM_BCM40
   `undef RM_BCM41
   `undef RM_BCM42
   `undef RM_BCM43
   `undef RM_BCM43_NRO
   `undef RM_BCM44
   `undef RM_BCM44_NRO
   `undef RM_BCM46_A
   `undef RM_BCM46_AA
   `undef RM_BCM46_B
   `undef RM_BCM46_C
   `undef RM_BCM46_D
   `undef RM_BCM46_E
   `undef RM_BCM46_F
   `undef RM_BCM47
   `undef RM_BCM48
   `undef RM_BCM48_DM
   `undef RM_BCM48_SV
   `undef RM_BCM49
   `undef RM_BCM49_SV
   `undef RM_BCM50
   `undef RM_BCM51
   `undef RM_BCM52
   `undef RM_BCM53
   `undef RM_BCM54
   `undef RM_BCM55
   `undef RM_BCM55_C
   `undef RM_BCM56
   `undef RM_BCM57
   `undef RM_BCM58
   `undef RM_BCM59
   `undef RM_BCM60
   `undef RM_BCM62
   `undef RM_BCM63
   `undef RM_BCM64
   `undef RM_BCM64_TD
   `undef RM_BCM65
   `undef RM_BCM65_ATV
   `undef RM_BCM65_TD
   `undef RM_BCM66
   `undef RM_BCM66_EFES
   `undef RM_BCM71
   `undef RM_BCM72
   `undef RM_BCM73
   `undef RM_BCM74
   `undef RM_BCM76
   `undef RM_BCM77
   `undef RM_BCM78
   `undef RM_BCM79
   `undef RM_BCM85
   `undef RM_BCM86
   `undef RM_BCM87
   `undef RM_BCM90
   `undef RM_BCM95
   `undef RM_BCM95_E
   `undef RM_BCM95_I
   `undef RM_BCM95_IE
   `undef RM_BCM98
   `undef RM_BCM99
   `undef RM_BCM99_N
   `undef RM_BVM01
   `undef RM_BVM02
   `undef RM_SVA01
   `undef RM_SVA02
   `undef RM_SVA03
   `undef RM_SVA04
   `undef RM_SVA05
   `undef RM_SVA06
   `undef RM_SVA07
   `undef RM_SVA08
   `undef RM_SVA09
   `undef RM_SVA10
   `undef RM_SVA11
   `undef RM_SVA12_A
   `undef RM_SVA12_B
   `undef RM_SVA12_C
   `undef RM_SVA99
   `undef SIM_REORDER
   `undef SNF_MODE
   `undef SNPS_RCE_INTERNAL_ON
   `undef __GUARD__DW_AXI_A2X_ALL_INCLUDES__VH__
   `undef __GUARD__DW_AXI_A2X_BCM_PARAMS__VH__
   `undef __GUARD__DW_AXI_A2X_CC_CONSTANTS__VH__
   `undef __GUARD__DW_AXI_A2X_DEFINE_CONSTANTS__VH__
`define cb_dummy_parameter_definition 1
`undef  cb_dummy_parameter_definition
